### ISSUE TITLE
Token balance display

### ISSUE THREAD

**Issue by Znozftw** [CodeWithJoe2020/sellTokenPancakeSwap#3]
Lines 47-48
readable = web3.fromWei(balance,'ether')
print("Balance: " + str(web3.fromWei(readable, 'ether')) + " " + symbol)

**Aren't we using .fromWei() method twice in this case?** - 1st time in "readable" and 2nd time later when we print balance.
Tested it with 0.33 BUSD account - with code above it displays 3.30 BUSD, and if I enter to sell 1 BUSD it will end with error.

If we change 48 line with: print("Balance: " + str(**readable**) + " " + symbol)
It will display correct balance (0.33 BUSD in my case, with no errors if I sell 0.1 BUSD).

**Comment by CodeWithJoe2020** [comment]
ok fixed
